# Generated by Django 3.0.2 on 2020-04-14 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0002_auto_20200401_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='img',
            field=models.ImageField(default='uploads\\coffee.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
