# Generated by Django 3.0.2 on 2020-04-16 15:49

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20200414_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
