# Generated by Django 3.0.2 on 2020-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20200416_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(max_length=50),
        ),
    ]
