# Generated by Django 3.0.2 on 2020-04-18 10:56

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20200416_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
