# Generated by Django 3.0.2 on 2020-04-18 11:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20200418_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='content',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
