# Generated by Django 3.0.2 on 2020-04-18 11:41

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20200418_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
